# cpp01 Makefile

# compile all exercises
all: 
	@echo "Compile all exercises"
	@$(MAKE) -C ex00
	@$(MAKE) -C ex01
	@$(MAKE) -C ex02
	@$(MAKE) -C ex03
	@$(MAKE) -C ex04
	@$(MAKE) -C ex05
	@$(MAKE) -C ex06

clean:
	@echo "Clean all exercises"
	@$(MAKE) -C ex00 clean
	@$(MAKE) -C ex01 clean
	@$(MAKE) -C ex02 clean
	@$(MAKE) -C ex03 clean
	@$(MAKE) -C ex04 clean
	@$(MAKE) -C ex05 clean
	@$(MAKE) -C ex06 clean

fclean:
	@echo "Fclean all exercises"
	@$(MAKE) -C ex00 fclean
	@$(MAKE) -C ex01 fclean
	@$(MAKE) -C ex02 fclean
	@$(MAKE) -C ex03 fclean
	@$(MAKE) -C ex04 fclean
	@$(MAKE) -C ex05 fclean
	@$(MAKE) -C ex06 fclean

re: fclean all

.PHONY: all ex00 ex01 ex02 ex03 ex04 ex05 ex06 clean re